version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_PASSWORD=pass123
  test-db:
    image: postgres
    restart: always
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_PASSWORD=pass123
